### PR TITLE
Fix invalid self-closing <span /> tag incompatible with jQuery 3.5

### LINKED ISSUE #558: jQuery 3.4.1 -> 3.5.0 breaks palette layout
with jQuery 3.4.1 it properly lays out the spans of the palette. 

with jQuery 3.5.0 the palette spans are created inside each other on each row.

### PR DESCRIPTION
**Pull request by andersk**
To close a cross-site scripting vulnerability, jQuery 3.5.0 disabled an insecure `htmlPrefilter` that previously fixed up invalid self-closing tags. Fix our HTML not to rely on that.

https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/

Fixes #558.

### CODE REVIEW

**Comment by nguyenj** [comment]
@bgrins any chance we can get this merged soon? The jQuery 3.5 patch release is a security patch and it exposed a regression in this plugin.

**Comment by thenitai** [comment]
We've only just updated to jQuery 3.5.1 and I was searching for hours for a solution. Thanks for the fix.

File: spectrum.js [hunk 1]
```diff
@@ -140,7 +140,7 @@
                 c += (tinycolor.equals(color, current)) ? " sp-thumb-active" : "";
                 var formattedString = tiny.toString(opts.preferredFormat || "rgb");
                 var swatchStyle = rgbaSupport ? ("background-color:" + tiny.toRgbString()) : "filter:" + tiny.toFilter();
-                html.push('<span title="' + formattedString + '" data-color="' + tiny.toRgbString() + '" class="' + c + '"><span class="sp-thumb-inner" style="' + swatchStyle + ';" /></span>');
+                html.push('<span title="' + formattedString + '" data-color="' + tiny.toRgbString() + '" class="' + c + '"><span class="sp-thumb-inner" style="' + swatchStyle + ';"></span></span>');
```
Comment (rafpaf) [inline spectrum.js:143]: 🙏 Thank you, Anders!

**Comment by bgrins** [comment]
Thanks for the patch, and sorry for the delay. I'll merge it now and tag a release later.

**Comment by bgrins** [comment]
1.8.1 has been tagged and published. I've also updated the docs page at https://bgrins.github.io/spectrum/ to use jQuery 3.5.1.
